#!/bin/bash
#include <stdio.h>

/**
   * main - Entry point
    *
     * Return: Always 0 (Success)
     * puts - prints line to standard output
      */
int main()
{
	puts("Programming is like bulding a multilingual puzzle\n")
	    return (0);
}
